/// Enumeration of all detectable ECG events and anomalies.
/// 
/// These event types are generated by signal processing layer (Dev D)
/// and indicate clinically significant features or artifacts in the ECG signal.
enum EcgEventType {
  /// Premature Ventricular Contraction - early heartbeat originating in ventricles
  pvc,
  
  /// Pause - abnormal gap in heartbeat sequence
  pause,
  
  /// Tachycardia - abnormally fast heart rate (typically >100 BPM)
  tachycardia,
  
  /// Bradycardia - abnormally slow heart rate (typically <60 BPM)
  bradycardia,
  
  /// Artifact - noise or interference in the signal (motion, poor contact, etc.)
  artifact,
  
  /// Lead-off - electrode contact loss detected by device (flags.bit0 or flags.bit1)
  leadOff,
}
